services:
  - type: web
    name: ai-video-creator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

# apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt